kind: pipeline
type: docker
name: REACTAPP


trigger:
  event:
    - push

steps:
  - name: app-build
    image: node:latest
    commands:
      - cd ./src/
      - npm install
      - npm run start
      
  - name: code-analysis
    image: node:latest
    environment:
      SONAR_TOKEN:
        from_secret: SECRET_TOKEN
    settings:
      sources: ./src/ 
    commands:
      - export SONAR_SCANNER_VERSION=4.7.0.2747
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"
      - sonar-scanner -D sonar.projectKey=react-auth-app -D sonar.sources=. -D sonar.host.url=https://codefirst.iut.uca.fr/sonar
    depends_on: [ app-build ]